#!/usr/bin/env python3
"""
ATTOM API
https://api.developer.attomdata.com
"""

HINSDALE = "HINSDALE, IL"

MADISON_HINSDALE = {}

HOMES = {
  "216 S MADISON ST": HINSDALE,
  "607 S ADAMS ST": HINSDALE,
  "428 MINNEOLA ST": HINSDALE,
  "600 S BRUNER ST": HINSDALE,
  "637 S BRUNER ST": HINSDALE,
  "142 S STOUGH ST": HINSDALE,
  "106 S BRUNER ST": HINSDALE,
  "37 S STOUGH ST": HINSDALE,
  "840 S ADAMS ST": HINSDALE,
  "618 S QUINCY ST": HINSDALE,
  "904 S STOUGH ST": HINSDALE,
  "222 CENTER ST": HINSDALE,
  "602 S ADAMS ST": HINSDALE,
  "18 E NORTH ST": HINSDALE,
  "818 S MADISON ST": HINSDALE,
  "427 N MADISON ST": HINSDALE,
  "317 E CHICAGO AVE": HINSDALE,
  "2 S BRUNER ST": HINSDALE,
  "133 S QUINCY ST": HINSDALE,
  "410 S MADISON ST": HINSDALE,
  "113 MAUMELL ST": HINSDALE,
  "138 E MAPLE ST": HINSDALE,
  "819 W 8TH ST": HINSDALE,
  "519 E 1ST ST": HINSDALE,
  "733 N ELM ST": HINSDALE,
  "603 JEFFERSON ST": HINSDALE,
  "729 JEFFERSON ST": HINSDALE,
  "731 TOWN PL": HINSDALE,
  "233 S QUINCY ST": HINSDALE,
  "238 S MADISON ST": HINSDALE,
  "718 W 4TH ST": HINSDALE,
  "209 S MADISON ST": HINSDALE,
  "415 N COUNTY LINE RD": HINSDALE,
  "111 S STOUGH ST": HINSDALE,
  "818 W HINSDALE AVE": HINSDALE,
  "712 S STOUGH ST": HINSDALE,
  "650 S THURLOW ST": HINSDALE,
  "134 MAUMELL ST": HINSDALE,
  "508 HIGHLAND RD": HINSDALE,
  "411 S STOUGH ST": HINSDALE,
  "431 S QUINCY ST": HINSDALE,
  "442 S QUINCY ST": HINSDALE,
}
