#!/usr/bin/env python3
"""
ATTOM API
https://api.developer.attomdata.com
"""

CLARENDON_HILLS = "CLARENDON HILLS, IL"
HINSDALE = "HINSDALE, IL"
LA_GRANGE = "LA GRANGE, IL"
WESTERN_SPRINGS = "WESTERN SPRINGS, IL"

HOMES = {
  "432 NAPERVILLE RD": CLARENDON_HILLS,
  "211 S PROSPECT AVE": CLARENDON_HILLS,
  "230 COE RD": CLARENDON_HILLS,
  "216 S MADISON ST": HINSDALE,
  "607 S ADAMS ST": HINSDALE,
  "428 MINNEOLA ST": HINSDALE,
  "1143 S SPRING AVE": LA_GRANGE,
  "645 MADISON AVE": LA_GRANGE,
  "608 S KENSINGTON AVE": LA_GRANGE,
  "4464 HOWARD AVE": WESTERN_SPRINGS,
  "4046 HARVEY AVE": WESTERN_SPRINGS,
  "4628 GRAND AVE": WESTERN_SPRINGS,
}
